# if using docker run command
# docker run -it --rm -d --name task-management -p 5432:5432 -e POSTGRES_USER=rizeki -e POSTGRES_PASSWORD=rifandani -e POSTGRES_DB=task-management postgres:latest

# docker-compose -f docker-compose.yml up -d
# then, visit http://localhost:8080
version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .db.env
    volumes:
      - postgres-data:/var/lib/postgresql/data/
      # - ./host-folder/:/var/lib/postgresql/data/
      # The data will be stored on the host computer, delete it with => rm -rf ./host-folder/

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080

# persist data even if container shuts down
# destroy volume and its data => docker-compose down --volumes
volumes:
  postgres-data:
